### ISSUE TITLE
Question regarding to replicate the experiment

### ISSUE THREAD

**Issue by bazingagin** [facebookresearch/meta_seq2seq#1]
Thanks for the great work. I have a few questions regarding to the code:

1. To replicate the result in Section 4.3 of the paper, shouldn't the code below be replaced by: 
```scan_all = ge.load_scan_file('addprim_jump','train')```? And same change should be applied to `scan_all_var = ge.load_scan_var('all','train')` too?
https://github.com/facebookresearch/meta_seq2seq/blob/59c3b4aafebf387bcd4e45626d8d91b66e6e5dff/train.py#L426

2. I'm a little confused about the "support set" in the experiment. According to the example in the paper, the support set seems to be carefully picked to cover the "prim" that will appear in the Query Input. However, according to the code below, it seems like the support set is not very different from query(command), at least for section 4.3. I'm wondering does that mean what's included in the support set is not very important?

```
D_query = scan_tuples_variable[:nquery]
D_support = scan_tuples_variable[nquery:nquery+nsupport]
```

**Comment by brendenlake** [comment]
Thanks for your questions. With regards to 1), the code as provided is correct. You need access to the SCAN "all" file in order to generate the permuted versions of the world that is used for meta-training.

For 2), it's a good observation that the support set used for meta-training is different than that used at meta-test, where just the primitives are given in support. That's right, I interpret it to mean that what's included in the support set is not very important. Lots of different variants work.
